# This file was generated by GoReleaser. DO NOT EDIT.
cask "fwrd" do
  name "fwrd"
  desc "A terminal-based RSS aggregator built with Go and Charm.sh tools"
  homepage "https://github.com/pders01/fwrd"
  version "1.65.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fwrd"

  on_macos do
    on_intel do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_darwin_amd64.tar.gz"
      sha256 "df26055dc8b34983dd474e0c74f04b307eea204604b114a449435b78692cd40c"
    end
    on_arm do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_darwin_arm64.tar.gz"
      sha256 "665fd2557686ae622296dadf7ea2bb6120a403d8e2bab7f8895c2fb8c31fe5d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_linux_amd64.tar.gz"
      sha256 "0edff28d08d8dd44215bbed9d4b1945e3cdf522ea891c7d7d8da297eab398388"
    end
    on_arm do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_linux_arm64.tar.gz"
      sha256 "4250439c8a8387d663f05bdd607790c4d24b7eba56e31a772b6a54e8c88b1633"
    end
  end

  caveats do
    "On macOS, binaries from third-party taps may be quarantined."
    "If needed, remove quarantine (adjust the path as needed):"
    "  xattr -dr com.apple.quarantine /opt/homebrew/bin/fwrd"
    "  xattr -dr com.apple.quarantine /usr/local/bin/fwrd"
  end

  # No zap stanza required
end
