# This file was generated by GoReleaser. DO NOT EDIT.
cask "fwrd" do
  name "fwrd"
  desc "A terminal-based RSS aggregator built with Go and Charm.sh tools"
  homepage "https://github.com/pders01/fwrd"
  version "1.56.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fwrd"

  on_macos do
    on_intel do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_darwin_amd64.tar.gz"
      sha256 "958e4bf405637269cd9afd95d1ab8f2f91d6428d82280b19318a5b64e0258f5e"
    end
    on_arm do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_darwin_arm64.tar.gz"
      sha256 "28ebafeb0aa90ea4d729d32b89254c70f1814efdcf56f6a361d2dd5f05d0a2ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_linux_amd64.tar.gz"
      sha256 "efafba283a03454cbbfb846678cfdb2677efe48a0f76c9fc7a81e228c22f3583"
    end
    on_arm do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_linux_arm64.tar.gz"
      sha256 "5163c3db08ff45519b93fbff98645a81d3bdfdbb3dd96d89b3f9d18008f129a0"
    end
  end

  caveats do
    "On macOS, binaries from third-party taps may be quarantined."
    "If needed, remove quarantine (adjust the path as needed):"
    "  xattr -dr com.apple.quarantine /opt/homebrew/bin/fwrd"
    "  xattr -dr com.apple.quarantine /usr/local/bin/fwrd"
  end

  # No zap stanza required
end
