# This file was generated by GoReleaser. DO NOT EDIT.
cask "fwrd" do
  name "fwrd"
  desc "A terminal-based RSS aggregator built with Go and Charm.sh tools"
  homepage "https://github.com/pders01/fwrd"
  version "1.66.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fwrd"

  on_macos do
    on_intel do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_darwin_amd64.tar.gz"
      sha256 "70c0024ae263db52063efe06ece32361918e5085175bde71e21a693532ce750b"
    end
    on_arm do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_darwin_arm64.tar.gz"
      sha256 "3922232d776208702c865c107694ec13ccb5e09e8136e63d98793d66a1e77f3e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_linux_amd64.tar.gz"
      sha256 "ff773f2a45242292c0aea1e61853dc666fa141db3f15a88d24b03735718952b1"
    end
    on_arm do
      url "https://github.com/pders01/fwrd/releases/download/v#{version}/fwrd_#{version}_linux_arm64.tar.gz"
      sha256 "2c18d3cbfc3afead23c078ce66c7a29bd96085811e65a78347d1c07712bc866c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fwrd"]
    end
  end

  # No zap stanza required
end
